fastify/fastify-websocket

.travis.yml
package-lock.json
package.json

Updates the dependencies to their latest available version, except for `tap` (updated to version 12.7.0 in order to preserve Node 6 support).
I added `tap` to Greenkeeper ignore list too.

Add Node 12 to CI and update dependencies

---

README.md
index.js
test/router.js

The `find-my-way` router already supports parsing route params.This PR simply passes the extracted route params on into the route handler, so that they can be used and don't have to be parsed again.

Pass route params to handlers.

---

.travis.yml
README.md
index.js
package.json
test/base.js
test/router.js

Continue of PR #34 
Fixed tests.
This potentially introduces breaking change. As `ws`'s `createWebSocketStream` returns node.js stream without any additional props that were in `websocket-stream` I've replaced old `connection` with object that contains two properties: `stream` - websocket stream and `socket` which refers to websocket instance. Actually it's possible just to add socket to node stream object that `createWebSocketStream` returns, but I'd rather prefer to keep it as is.
@mcollina, @Eomm please review and tell if you're okay with such change or not. And after that I continue with updating docs and probably rewriting `verifyClient`, cause it's deprecated and may be removed soon.
PS: Current ws version doesn't support node 6, and I think that this plugins should also drop it's …

Migrate to ws (continue)

---

index.d.ts
package.json
test/types/index.test-d.ts
tsconfig.json

Added types.
TODO: add tests and comments (will do in a few days). But if anyone wants to proceed - fell free to take typedefs from this PR and proceed. 
Closes #37.

feat(typescript): add initial types

---

index.d.ts
test/types/index.test-d.ts

Hello 👋 
First of all, thanks @mcollina, @delvedor & all contributors for the awesome `fastify` ecosystem. I had just recently dived into it & I'm very impressed.
Moving on to the issue on hand, I found out that the TS typing provided for `PluginOptions` (used in `fastify.register(ws, opts \*here*\)` is incorrect: **the typings requires both `handler` and `options` to be passed in**. I looked into the docs & code to verify that it has defaults specified.
I fixed this in this PR, and had added tests to cover this use-case. Additionally, I did minor clean-up on the declaration file.
I think this addresses #47 too.

Fix PluginOptions incorrect typings

---

index.js
test/router.js

I fixed the error addressed on this issue [61](https://github.com/fastify/fastify-websocket/issues/61)
> Method 'GET' already declared for route '/<prefix>'
caused by setting empty get path route `fastify.get('/', <function>)` after registering with prefix.
and websocket will register two paths `<prefix>` and `<prefix/>` and two handler. which causes this error.
p.s. This is my first PR ever! so if something is not right, I would be thankful if you could guide me :)
- [✓ ] run `npm run test` and `npm run benchmark`
- [ ✓] tests and/or benchmarks are included
- [ ✓] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

fixed Method 'GET' already declared for route Error

---

index.d.ts
test/types/index.test-d.ts

In the README it states (and in my experience also) the handler doesn't get a full on `FastifyRequest` object. It gets an `http.IncomingMessage` instead! This makes the TypeScript types reflect that.

Update TypeScript types to match actual request object passed to handlers

---

index.js
test/base.js

As noted by @franky47 in #45, the http server close callback does not fire until all connections are closed. This works extremely well for http requests, because it allows to wait until everything is done. It does not work well for websockets, because we need to call a method in each of them `close()`, hence I monkeypatch the server.close method.
I think we should send a PR to fastify to add the ability to handle this specific case.
This is a draft PR because the behavior should likely be customizable, i.e. the `client.close()` accepts a code and a message.
Fixes #45.

Send a close to all websocket connections when server closes

---

README.md
index.d.ts
index.js
test/router.js
test/types/index.test-d.ts

Exposes fastify server in global and per route websocket handlers via `this` binding.
Adds tests to ensure this is the case in both kinds of handlers.
Adds a note in README to alert users about fastify request lifecycle expectations and clue them into the exposed server inside han dlers.
The typings for per route handlers seemed to already declare that `this` was bound to the fastify instance even if in reality that was not the case.
Fixes #66

expose fastify server in websocket handlers

---

index.d.ts
package.json
test/types/index.test-d.ts

This corrects an issue introduced in #64 where upon adding `fastify-websocket` to a project all route handlers were (accidentally) assumed to be websocket handlers getting the different (and decidedly less useful) types. My bad! This corrects the issue by using a type-land overload of the RouteShorthand function definition to change the type of the handler only if the handler is in fact `{ websocket: true }`.
Also adds tests, `tsd` is handy!

Ensure websocket handler types are only applied to websocket handlers

---

package.json
test/router.js

closes #69 
```
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
index.js |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
```

Added test that covers error inside async handler.

---

index.d.ts
test/types/index.test-d.ts

Fixes https://github.com/fastify/fastify-websocket/issues/72
@TriangularCube can you please check if this works?

Maybe fix types

---

index.js
test/base.js

This fixes #77 by resuming the connection before calling the handler.

fix: Resume connection before continuing. [#77]

---

index.js
test/base.js

Resume connection stream before continuing.

---

index.js
test/base.js

The property server is only set, when noServer is null or false.
https://github.com/fastify/fastify-websocket/issues/88

Setting noServer has no effect

---

package.json

Bumps `find-my-way` dependency to a minimum version of `3.0.5` in order to resolve this security alert:
https://github.com/advisories/GHSA-jgrh-5m3h-9c5f
```
Suites:   2 passed, 2 of 2 completed
Asserts:  65 passed, of 65
```
- [✅] run `npm run test` and `npm run benchmark`
- [✅] tests and/or benchmarks are included
- [✅] documentation is changed or added
- [✅] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)

Bump find-my-way to 3.0.5

---

README.md
index.d.ts
index.js
package.json
test/base.js
test/hooks.js
test/router.js
test/types/index.test-d.ts

This is about [fastify/fastify-websocket/#70](https://github.com/fastify/fastify-websocket/issues/70), it closes #70 and is dependent on the changes here [fastify/fastify/#2733](https://github.com/fastify/fastify/pull/2733)
- removes the internal find-my-way router used for websocket routes
- dispatches websocket incoming connections through the normal fastify request cycle
- runs all hooks up to handler execution
- allows access to FastifyRequest object inside websocket handlers
- In order to run the hooks and create the necessary internals objects `FastifyRequest`, `FastifyReply`, and `Context`, the incoming connection needs to be dispatched to the fastify instance router. This was done by updating the fastify repository in order to expose the routing utility (precisely the …

Adding support for hooks/decorators by using FastifyRequest for websocket handlers

---

index.js
test/base.js

This avoids any race conditions where new websocket connections come in between the loop that closes all existing clients and the server no longer listening for new connections.
We observed this in one of our end-to-end test suites, where we have some out-of-process services that use reconnecting websockets. Setting up a `setInterval` that printed `server.clients.size` showed that it was not empty before this change, but was empty after this change.
@mcollina thought you'd be interested in seeing this one, since you introduced this code :)

Close the fastify server before closing clients.

---

README.md
index.js
test/base.js
test/hooks.js

New in version `3.0.0`, we run the fastify hooks for the request before handing the constructed websocket over to the route handler. Before this change, `fastify-websocket` processed the `UPGRADE` request from the client before dispatching the request to the router. This means it created the `WebSocket` object and the duplex stream wrapping it before invoking all the userland code that might want to do stuff in hooks like authentication, or loading a session, or whatever. 
If those hooks that run after the creation of the websocket are asynchronous, that means that the websocket that has already been set up and connected can receive messages during the execution of those async hooks. Generally I think developers would attach onMessage handlers in their route handler functions. If they do …

Don't lose messages when hooks are asynchronous

---

index.d.ts
test/types/index.test-d.ts

Improves typing of the ws request handler. Passing generics here allows typing params, e.g. 
```ts
fastify.get<{ Params: { id: string } }>(
'/:id',
{ websocket: true },
(conn, req) => {
req.params.id // typechecks!
}
)
```
- [] documentation is changed or added

Improve request type in ws handler

---

index.js
test/base.js

fixes #119
I basically duplicated the other test and removed the `async` keyword. Without the fix the test would timeout.

Run error handler when an error occurs in a non-async handler

---

index.js
test/base.js
test/router.js

Fixes https://github.com/fastify/fastify-http-proxy/issues/152
Fixes https://github.com/fastify/fastify-http-proxy/pull/155

Preserve the prefix in nested plugins

---

index.js
test/base.js

Hi, 
I found that if I have the websocket option `clientTracking` in false it throws an error during the `server.close()` because `server.clients` is undefined and the plugin expect always an iterable.
Checking for the server.clients undefined fix the issue.

check for server.clients undefined

---

.github/workflows/ci.yml
package.json

ws back to ^7
Ref: 
https://github.com/fastify/fastify-websocket/pull/137
Then we should release this as bugfix but @DRoet should revert the application's changes

revert dep major bump

---

README.md

Replaces #105 with some documentation. 

Document installing @types/ws for TS users

---

test/hooks.js

Hello.
- Remove `preParsing` references from tests (https://github.com/fastify/fastify/issues/3503)

test: prepare plugin for fastify 4.x

---

package.json
test/hooks.js

Hello.
Following [this discussion](https://github.com/fastify/fastify/issues/3503), this PR aims to :
- add back `preParsing` hook tests
- upgrade package dependencies

test: add back `preParsing` hook tests

---

README.md
index.js
test/hooks.js

This change fixes a bug in fastify-websocket where the `reply` object wouldn't actually send anything if it was asked to -- the only think you could do with it is hijack it. Before this change, if you tried to do reply.send or reply.code or what have you, those bytes would never make it out the client. I tested with browsers and with wsocat. The effect of this is that if someone is using an error handler to send errors as HTTP responses, or a validation handler that authenticates or something like that, those responses never make it to the client, but fastify considers the reply sent and is finished with it, leaving hanging sockets and broken expectations.
I think this is an accidental change introduced in #95 when we switched this library to start using fastify's routing and creating …

Ensure that hooks and error handlers can send standard HTTP replies

---

index.d.ts
test/types/index.test-d.ts

This replaces and finishes the work started in #128 by adding some tests!

Generic route options

---

index.js

I have added a few lines of code to add a `req.ws` boolean for if the request was an upgrade for websocket.

Add `req.ws`

---

index.d.ts
test/types/index.test-d.ts

Added this property in #163, but didn't add it to the typedefs, this finishes that.
Adds tests on top of and replaces #180 

Add `request.ws` to type definitions

---

test/hooks.js
test/router.js

style: use property shorthand

---

.github/workflows/ci.yml
README.md
index.d.ts
index.js
package.json
test/base.js
test/hooks.js
test/router.js

Signed-off-by: Matteo Collina <hello@matteocollina.com>

Update to Fastify v4

---

index.js
test/hooks.js

Signed-off-by: Matteo Collina <hello@matteocollina.com>

Fix done is undefined error

---

README.md
index.js
test/hooks.js

`fastify-websocket` has rich support for running requests through the router and hooks before actually upgrading them to full duplex websocket connections outside the normal HTTP lifecycle. Hooks are useful for auth, sessions, tracing, etc etc, and so we take care to make the request look as normal as possible until we `reply.hijack()` and take over.
Before this change, the `onError` hook that `fastify-websocket` was registering was very eagerly handling errors encountered during the hook chain. The `onError` hook would run *before* any error handlers added by `.setErrorHandler`, and it would by-default upgrade the request to dispatch a close code. This changed with the upgrade to fastify v4 -- before, any error in a hook would run the `.setErrorHandler` errors first, which would probably …

Ensure that setErrorHandler functions run for errors thrown before the websocket is upgraded

---

index.d.ts
package.json
test/types/index.test-d.ts

https://github.com/fastify/fastify-websocket/issues/213
Fixed TypeProvider typings in its WebsocketHandler by adding SchemaCompiler, TypeProvider, and Logger.  Attempted to mirror the style used in fastify route.d.ts.

Added SchemaCompiler, TypeProvider, and Logger to types.

---

index.js
test/base.js

Some safari browsers are buggy and set some bits without negotiating them with the server.
This cause the server crash with:
```
code: "WS_ERR_UNEXPECTED_RSV_2_3"
message: "Invalid WebSocket frame: RSV2 and RSV3 must be clear"
stack: "RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
at Receiver.getInfo (/app/node_modules/ws/lib/receiver.js:176:14)
at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:136:22)
at Receiver._write (/app/node_modules/ws/lib/receiver.js:83:10)
at writeOrBuffer (node:internal/streams/writable:392:12)
at _write (node:internal/streams/writable:333:10)
at Writable.write (node:internal/streams/writable:337:10)
at Socket.socketOnData (/app/node_modules/ws/lib/websocket.js:1272:35)
at Socket.emit (node:events:513:28)
at addChunk …
```

fix/ws-error-handler - Handle WebSocket errors to avoid Node.js crashes
